// air
#declare Block0Material = material { texture { } }

// lava
#declare Block10Material = material { texture {
	 
	 pigment {Orange}
} }
 
// lava
#declare Block11Material = material { texture {
	 
	 pigment {Orange}
} }

// gold ore
#declare Block14Material = material { texture {
	 
	 pigment {Grey}
} }

// lapis lazuli ore
#declare Block21Material = material { texture {
	 
	 pigment {Grey}
} }

// wool
#declare Block35Material = material { texture {
	 
	 pigment {White}
} }

// red mushroom
#declare Block40Material = material { texture { } }

// gold
#declare Block41Material = material { texture {
	 
	 pigment {Yellow}
} }

// iron
#declare Block42Material = material { texture {
	 
	 pigment {Grey}
} }

// double slab
#declare Block43Material = material { texture {
	 
	 pigment {Grey}
} }

// slab
#declare Block44Material = material { texture { } }

// moss stone
#declare Block48Material = material { texture {
	 
	 pigment {Grey}
} }

// obsidian
#declare Block49Material = material { texture {
	 
	 pigment {Grey}
} }

// torch
#declare Block50Material = material { texture { } }

// diamond ore
#declare Block56Material = material { texture {
	 
	 pigment {Grey}
} }

// wooden door
#declare Block64Material = material { texture { } }

// rails
#declare Block66Material = material { texture { } }

// wall sign
#declare Block68Material = material { texture { } }
